### PR TITLE
Julia 0.6 fixes

### PR DESCRIPTION
**Pull request by amgad-naiem**
Based on the comments of your PR in https://github.com/JuliaDB/PostgreSQL.jl/pull/48#discussion_r89632468 & the fact that `unsafe_string` support only `::Ptr{UInt8}`. The function that replaces `bytestring(s)` is `String(s)` Check [here](https://docs.julialang.org/en/release-0.6/stdlib/strings/?highlight=bytestring#Core.String-Tuple{AbstractString})

Also it included julia 0.6 depreciation fixes. There are many commits that represent my trials into going about this earlier :)

### CODE REVIEW

**Comment by wookay** [comment]
could you squashing commits?

**Comment by amgad-naiem** [comment]
Can you squash when doing the merge ?

**Comment by wookay** [comment]
oh. I'm not a maintainer of PostgreSQL.jl. Hopefully this PR needs the review and test by other maintainers. it would be better to have the tests for `storestring`, `pgdata` because I didn't have enough test for them.

**Comment by amgad-naiem** [comment]
I thought you would merge it here and will be effective in your PR to PostgreSQL.jl, but it's okay I can make a PR there

**Comment by wookay** [comment]
ok, I try to merge it here.

**Pull request merged**
